### ISSUE TITLE
Any idea what this is about? ):

### ISSUE THREAD

**Issue by VoyagerXyX** [Jakubson/ProjectAreas#1]
[16:00:28 ERROR]: Error occurred while enabling ProjectAreas v3.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.LEGACY_
	at java.lang.Enum.valueOf(Enum.java:240) ~[?:?]
	at org.bukkit.Material.valueOf(Material.java:89) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.valueOf(CraftLegacy.java:227) ~[patched_1.16.5.jar:git-Paper-457]
	at com.projectareas.jakubson.system.ArenaManager.loadArenas(ArenaManager.java:120) ~[?:?]
	at com.projectareas.jakubson.ProjectAreas.onEnable(ProjectAreas.java:110) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-457]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-457]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Jakubson** [comment]
Hi, I only give support on SpigotMC. Please contact with me there and I will try to help you: https://www.spigotmc.org/conversations/add?to=Jakubson
